version: '3.0'

services:

  microservice:
    image: microservice
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
    - "3000:3000"

  db:
    image: postgres
    restart: always
    environment:
      # - POSTGRES_DB=example
      - POSTGRES_PASSWORD=password
    expose:
      - 5432